<?php
/**
 * @file
 * Custom code for the Caltech Library Collections module.
 */

/**
 * Implements hook_views_api().
 */
function caltechlibrary_collections_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'caltechlibrary_collections') . '/includes/views',
  );
}

/**
 * Implements hook_module_implements_alter().
 */
function caltechlibrary_collections_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'views_data_alter') {
    $group = $implementations['caltechlibrary_collections'];
    unset($implementations['caltechlibrary_collections']);
    $implementations['caltechlibrary_collections'] = $group;
  }
}

/**
 * Implements hook_node_view().
 */
function caltechlibrary_collections_node_view($node, $view_mode) {
  $links = array();

  if ($node->comment != COMMENT_NODE_HIDDEN) {
    if ($view_mode == 'teaser') {
      // Teaser view: display the number of comments that have been posted,
      // or a link to add new comments if the user has permission, the node
      // is open to new comments, and there currently are none.
      if (user_access('access comments')) {
        if (!empty($node->comment_count)) {
          $links['comment-comments'] = array(
            'title' => format_plural($node->comment_count, '1 comment', '@count comments'),
            'href' => "node/$node->nid",
            'attributes' => array('title' => t('Jump to the first comment of this posting.')),
            'fragment' => 'comments',
            'html' => TRUE,
          );
        }
      }
      if ($node->comment == COMMENT_NODE_OPEN) {
        if (user_access('post comments')) {
          $links['comment-add'] = array(
            'title' => t('add comment'),
            'href' => "node/$node->nid",
            'attributes' => array('title' => t('Add a new comment.')),
            'fragment' => 'comment-form',
          );
        }
        else {
          $links['comment_forbidden'] = array(
            'title' => theme('comment_post_forbidden', array('node' => $node)),
            'html' => TRUE,
          );
        }
      }
    }

    $node->content['links']['comment'] = array(
      '#theme' => 'links__node__comment',
      '#links' => $links,
      '#attributes' => array('class' => array('links', 'inline')),
    );

  }
}

/**
 * Implements hook_theme_registry_alter().
 */
function caltechlibrary_collections_theme_registry_alter(&$theme_registry) {
  if (!empty($theme_registry['comment_post_forbidden'])) {
    $theme_registry['comment_post_forbidden']['function'] = 'caltechlibrary_collections_comment_post_forbidden';
  }
}

/**
 * Customized version of the theme_comment_post_forbidden() function.
 *
 * Uses the login URL from `shib_auth` if available instead of `/user/login`.
 *
 * @param $variables
 *   An associative array containing:
 *   - node: The comment node.
 */
function caltechlibrary_collections_comment_post_forbidden($variables) {
  $node = $variables['node'];
  global $user;

  // Since this is expensive to compute, we cache it so that a page with many
  // comments only has to query the database once for all the links.
  $authenticated_post_comments = &drupal_static(__FUNCTION__, NULL);

  if (!$user->uid) {
    if (!isset($authenticated_post_comments)) {
      // We only output a link if we are certain that users will get permission
      // to post comments by logging in.
      $comment_roles = user_roles(TRUE, 'post comments');
      $authenticated_post_comments = isset($comment_roles[DRUPAL_AUTHENTICATED_RID]);
    }

    if ($authenticated_post_comments) {
      // We cannot use drupal_get_destination() because these links
      // sometimes appear on /node and taxonomy listing pages.
      if (variable_get('comment_form_location_' . $node->type, COMMENT_FORM_BELOW) == COMMENT_FORM_SEPARATE_PAGE) {
        $destination = array('destination' => "comment/reply/$node->nid#comment-form");
      }
      else {
        $destination = array('destination' => "node/$node->nid#comment-form");
      }

      if (module_exists('shib_auth')) {
        // We change the login links to use Shibboleth instead of Drupal.
        if (variable_get('user_register', USER_REGISTER_VISITORS_ADMINISTRATIVE_APPROVAL)) {
          // Users can register themselves.
          return t('<a href="@login">log in</a> or <a href="@register">register</a> to post comments', array('@login' => shib_auth_generate_login_url(), '@register' => url('user/register', array('query' => $destination))));
        }
        else {
          // Only admins can add new users, no public registration.
          return t('<a href="@login">log in</a> to comment', array('@login' => shib_auth_generate_login_url()));
        }
      }
      else {
        // We use the default functionality.
        if (variable_get('user_register', USER_REGISTER_VISITORS_ADMINISTRATIVE_APPROVAL)) {
          // Users can register themselves.
          return t('<a href="@login">log in</a> or <a href="@register">register</a> to post comments', array('@login' => url('user/login', array('query' => $destination)), '@register' => url('user/register', array('query' => $destination))));
        }
        else {
          // Only admins can add new users, no public registration.
          return t('<a href="@login">log in</a> to comment', array('@login' => url('user/login', array('query' => $destination))));
        }
      }
    }
  }
}

/**
 * Implements hook_block_info().
 */
function caltechlibrary_collections_block_info() {
  $blocks = array();
  $blocks['comment_login'] = array(
    'info' => t('Anonymous, log in to comment'),
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function caltechlibrary_collections_block_view($delta = '') {
  $block = array();
  switch($delta) {
    case 'comment_login' :
      $block['content'] = _caltechlibrary_collections_comment_login_helper();
      break;
  }
  return $block;
}

/**
 * Custom render function for comment_login block.
 */
function _caltechlibrary_collections_comment_login_helper() {
  $variables = array();
  $variables['node'] = menu_get_object();
  return caltechlibrary_collections_comment_post_forbidden($variables);
}

/**
 * Implements hook_filter_info_alter().
 */
function caltechlibrary_collections_filter_info_alter(&$info) {
  if (module_exists('mathjax')) {
    $info['filter_mathjax']['tips callback'] = '_caltechlibrary_collections_mathjax_filter_tips';
  }
}

/**
 * Filter tips callback for the mathjax filter.
 */
function _caltechlibrary_collections_mathjax_filter_tips($filter, $format, $long = FALSE) {
  return t('<span class="tex2jax_ignore">Mathematics are rendered by
    <a href="@url">MathJax</a>. The default math delimiters are $$…$$ and \[…\]
    for displayed mathematics, and $…$ and \(…\) for in-line mathematics. Type
    \$ for a literal dollar sign.</span>',
    array('@url' => url('https://www.mathjax.org/'))
  );
}
